### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/libtheora-feedstock#4]
Appears there are no Windows builds of `libtheora`. Though there does appear to be a `CMakeLists.txt` included for this purpose. Would it be possible to make Windows builds? Any known blockers?

**Comment by jakirkham** [comment]
Good to know there should be no technical blockers.

Think they are missing because of this [`skip` line]( https://github.com/conda-forge/libtheora-feedstock/blob/17159e99922cf93b38e988b411ff7456a9ec1041/recipe/meta.yaml#L14 ). Am trying to take it out and re-render.

**Comment by jakirkham** [comment]
Looks like inline assembly is required, but Window 64-bit's Visual Studio Compilers do not support this.

xref: https://github.com/conda-forge/libtheora-feedstock/pull/7#issuecomment-388646497

**Comment by jschueller** [comment]
@jakirkham looks like this one can be closed

**Comment by jakirkham** [comment]
Thanks @jschueller! Closed with PR ( https://github.com/conda-forge/libtheora-feedstock/pull/10 ).
